### ISSUE TITLE
Prediction script

### ISSUE THREAD

**Issue by JacobusS** [ec-jrc/GHS-S2Net#1]
Is it possible to provide the prediction script as well.
I'm having issues putting everything together to complete the process.

**Comment by misterspook** [comment]
Hi @JacobusS ,

yes, here it is:
https://github.com/ec-jrc/GHS-S2Net/blob/main/code/GHS_S2_run_prediction.py

**Comment by JacobusS** [comment]
> Hi @JacobusS ,
> 
> yes, here it is:
> https://github.com/ec-jrc/GHS-S2Net/blob/main/code/GHS_S2_run_prediction.py

Fantastic, thank you so much appreciate the help

**Comment by manapshymyr-OB** [comment]
> > Hi @JacobusS ,
> > yes, here it is:
> > https://github.com/ec-jrc/GHS-S2Net/blob/main/code/GHS_S2_run_prediction.py
> 
> Fantastic, thank you so much appreciate the help
were you able to run the training?
