### ISSUE TITLE
Is it possible to detect the built up on any tiff image?

### ISSUE THREAD

**Issue by manapshymyr-OB** [ec-jrc/GHS-S2Net#3]
Hello!
You did a great job.

I wanted to test the prediction over the Bayern area. Is it possible to do it? or I can do It only by UTM zones?

**Comment by misterspook** [comment]
Hi!
Thanks.

Check the comment in the prediction script:
#The Python script gets as input the 4-band Sentinel-2 image composite in 10 m spatial resolution. The order of the bands is 0: Band 4–Red; 1: Band 3–Green; 2: Band 2–Blue; 3: Band 8–NIR 
#This composite is available at:
#https://data.jrc.ec.europa.eu/dataset/0bd1dfab-e311-4046-8911-c54a8750df79

In case you have a Sentinel-2 image over Bayern area, it should work. Take care of the bands order and image preprocessing:

```
I2[I2>10000] = 10000
I2 = I2 / 10000.
```

**Comment by manapshymyr-OB** [comment]
@misterspook Can this prediction work with external tiff files? I mean with files, not from #https://data.jrc.ec.europa.eu/dataset/0bd1dfab-e311-4046-8911-c54a8750df79?

**Comment by misterspook** [comment]
Yes, it can, but they need to be from the Sentinel-2 sensor.

**Comment by manapshymyr-OB** [comment]
@misterspook 
```
I2[I2>10000] = 10000
I2 = I2 / 10000.
```
How the numbers must be chosen?
