### ISSUE TITLE
Is it possible to predict with low technical spec laptops?

### ISSUE THREAD

**Issue by manapshymyr-OB** [ec-jrc/GHS-S2Net#4]
Hello again! Is it possible to somehow run predict script with regular laptops?

My specs are:

I7-7700hq 2.8 GHz, 
RAM 16 GB, 
GPU: GTX1050Ti

Currently I am getting 

`numpy.core._exceptions.MemoryError: Unable to allocate 50.5 GiB for an array with shape (23296, 23296, 1, 5, 5, 1) and data type float32`

**Comment by misterspook** [comment]
Hello,

for a regular laptop, you would need to clip your large image so it can fit into the system RAM and then use a small batch size for the GPU RAM. Try with 1000x1000 pixels...

I would suggest to use google colab for large images:
https://colab.research.google.com/notebooks/intro.ipynb
, or a more powerful machine.

Also, your numpy array shape seems strange. Should be like this:
(23296, 23296, 4) _4bands_

and then when you reshape it for prediction:
(number_of_patches, 5, 5, 4)

**Comment by manapshymyr-OB** [comment]
@misterspook I downloaded data directly from the link you have included in the code.... I mean I have not changed anything

**Comment by misterspook** [comment]
You have to clip the image if you are going to use your laptop.
