### ISSUE TITLE
Using on different categories

### ISSUE THREAD

**Issue by manapshymyr-OB** [ec-jrc/GHS-S2Net#6]
Is it possible to use the model for other categories (forests, agriculture)?

**Comment by misterspook** [comment]
Yes, you can try and test it with different kind of training data.

**Comment by manapshymyr-OB** [comment]
@misterspook can you please send sample data that has been used for training specifically in this project. I am trying to adapt a new dataset according to the description, but facing several challenges. thanks in advance
